// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Get the Current week of the Month
 * @returns {Promise.<Big>}
 */
export async function CurrentWeekinMonth() {
	// BEGIN USER CODE
  var now = new Date();
  var firstWeekday = new Date(now.getFullYear(), now.getMonth(), 1).getDay();
  var offsetDate = now.getDate() + firstWeekday - 1;
  var CurrentWeekinMonth=(Math.floor(offsetDate / 7))+1;
  return CurrentWeekinMonth;
	
	//throw new Error("JavaScript action was not implemented");
	// END USER CODE
}
