// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Get the Month Start Date by passing the month and year
 * @param {Big} year
 * @param {Big} month
 * @returns {Promise.<Date>}
 */
export async function MonthStartDate(year, month) {
	// BEGIN USER CODE
	
	var CurrentMonthStartDate = new Date(year, month-1, 1);
	return CurrentMonthStartDate;
	
	//throw new Error("JavaScript action was not implemented");
	// END USER CODE
}
