// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Get the total number of weeks in a month
 * @param {Big} year
 * @param {Big} month
 * @returns {Promise.<Big>}
 */
export async function NoOfWeeksinMonth(year, month) {
	// BEGIN USER CODE

	 var now = new Date(year, (month-1), 1);
	 mx.logger.info('noe date::'+now);
	var firstDay = new Date(now.setDate(1)).getDay();
    var totalDays = new Date(now.getFullYear(), now.getMonth() + 1, 0).getDate();
	var numberofweeks=Math.ceil((firstDay + totalDays) / 7);
    return numberofweeks;
	//throw new Error("JavaScript action was not implemented");
	// END USER CODE
}
